name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check rustfmt
        if: success() || failure()
        run: nix develop --command cargo fmt --check
      - name: Check nixpkgs-fmt formatting
        if: success() || failure()
        run: nix develop --command nixpkgs-fmt --check .
      - name: Check build
        if: success() || failure()
        run: nix develop --command cargo build
      - name: Check tests
        if: success() || failure()
        run: nix develop --command cargo test
