name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache lint store (x86_64-linux)
        id: lint-store-x86_64-linux
        uses: actions/cache@v3
        with:
          path: ~/.ci-store
          key: lint-store-x86_64-linux-${{ hashFiles('**/Cargo.lock', '**/flake.lock') }}-v1
      - name: Check rustfmt
        run: nix develop --store ~/.ci-store --command cargo fmt --check
      - name: Check nixpkgs-fmt formatting
        run: nix develop --store ~/.ci-store --command nixpkgs-fmt --check .
      - name: Check build
        run: nix develop --store ~/.ci-store --command cargo build
      - name: Check tests
        run: nix develop --store ~/.ci-store --command cargo test
